name: Run Odoo tests

on:
  pull_request:
    branches:
      - dev

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: odoo
          POSTGRES_PASSWORD: odoo
          POSTGRES_DB: odoo
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python3 -m pip install -r requirements.txt
          pip install -e .

      - name: Read test modules from JSON
        id: read_modules
        run: |
          MODULES=$(python3 -c "import json; print(','.join(json.load(open('test_modules.json'))['modules']))")
          echo "modules_to_test=$MODULES" >> $GITHUB_OUTPUT

      - name: Run Odoo tests
        env:
          DB_HOST: localhost
          DB_PORT: 5432
          DB_USER: odoo
          DB_PASSWORD: odoo
        run: |
          ./odoo-bin -d test_db --db_host=$DB_HOST --db_user=$DB_USER --db_password=$DB_PASSWORD \
            --test-enable --stop-after-init -i ${{ steps.read_modules.outputs.modules_to_test }}
